### ISSUE TITLE
[BUG] Duplicate entries in search bar suggestions

### ISSUE THREAD

**Issue by LuLeRoemer** [eclipse-esmf/esmf-semantic-aspect-meta-model#44] opened 2021-07-02 13:02 UTC
**Describe the bug**
When typing a term into the search bar, the list with suggestions appearing underneath, contains duplicates for each released version (currently snapshot and 1.0.0).

**Where**
The search bar of the Antora documentation of BAMM.

**Screenshots**
![Screen Shot 2021-07-02 at 14 58 06](https://user-images.githubusercontent.com/19715293/124277938-ecfa8700-db45-11eb-8275-487b8046e3e6.png)

**Comment by atextor** [comment] 2021-08-16 06:46
Technically this is not a bug, but the search works across versions. So for each page of any version that matches the filter, a result is found. Obviously the current state is sub-optimal but we should clarify what we want here:
* Should the search only show results from the latest version of each component?
* Should the search result display the respective version inline?
* Something else?

**Comment by BirgitBoss** [comment] 2022-09-27 14:51
I think searching through all version might be interesting in some cases. So either
- allow restriction to current version
- and/or dispaly version in search result

**Comment by atextor** [comment] 2023-10-25 13:35
Fixed by https://github.com/eclipse-esmf/eclipse-esmf.github.io/pull/23

**Closed by atextor** 2023-10-25 13:35 UTC
Labels: bug, acknowledged
